
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

alexa:
  smart_home:
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: !secret alexa-id
    client_secret: !secret alexa-secret

calendar:
  - platform: caldav
    url: http://workcal:5232
    username: !secret caldav-user
    password: !secret caldav-password
